trigger:
  branches:
    include:
      - Log-in-test

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
    python -m pip install --upgrade pip
    pip install selenium pyperclip
    pip --version
  displayName: 'Verify dependencies'

- script: |
    # Verify ChromeDriver installation
    chromedriver --version
  displayName: 'Verify ChromeDriver'

- script: |
    # Check Chrome version
    google-chrome --version
  displayName: 'Check Chrome version'

- script: |
    # Debug: List directories to understand the structure
    ls -R $(Build.SourcesDirectory)
  displayName: 'List directories for debugging'

- script: |
    python mainV2.py 
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Run Python script'
