trigger:
  branches:
    include:
      - Log-in-test

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
    python -m pip install --upgrade pip
    pip install selenium pyperclip
  displayName: 'Install dependencies'

- script: |
    # Download ChromeDriver
    CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
    wget -q --continue -P /tmp https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
    unzip /tmp/chromedriver_linux64.zip -d /tmp
    sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
    sudo chmod +x /usr/local/bin/chromedriver
  displayName: 'Install ChromeDriver'

- script: |
    # Verify ChromeDriver installation
    chromedriver --version
  displayName: 'Verify ChromeDriver'

- script: |
    python main.py  # Adjust path and working directory as needed
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Run Python script'
